Getting started example doesn't compile.
Currently:
```
error[E0422]: cannot find struct, variant or union type `Model` in this scope
  --> src/main.rs:16:9
   |
16 |         Model { clicked: false }
   |         ^^^^^ not found in this scope
error: aborting due to previous error
For more information about this error, try `rustc --explain E0422`.
error: could not compile `stoksc-github-io`.
```
After change:

```
   Finished dev [unoptimized + debuginfo] target(s) in 1.65s
    Processing "stoksc-github-io.wasm"...
    Finished processing of "stoksc-github-io.wasm"!

If you need to serve any extra files put them in the 'static' directory
in the root of your crate; they will be served alongside your application.
You can also put a 'static' directory in your 'src' directory.

Your application is being served at '/stoksc-github-io.js'. It will be automatically
rebuilt if you make any changes in your code.

You can access the web server at `http://[::1]:8000`.
```